package server

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"

	"lazy/ReturnMessage"
	"lazy/config"
)

func GoTell(c *config.Client) *ReturnMessage.AutoGenerated {
	var (
		a = ReturnMessage.NewArticles("", "", "", "", "", "")
		s = ReturnMessage.NewSendMessage("", "", "", "", 0, *a, 0, 0, 0)
	)
	i, err := json.Marshal(s)
	if err != nil {
		return nil
	}
	req, err := http.Post(
		"https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token="+Gettoken(c).AccessToken,
		"application/json;charset=utf-8", bytes.NewBuffer(i),
	)
	if err != nil {
		fmt.Println(err)
	}
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {
		}
	}(req.Body)
	all, err := ioutil.ReadAll(req.Body)
	var result ReturnMessage.AutoGenerated
	err = json.Unmarshal(all, &result)
	return &result
}
